### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by KostyaSha** [jenkinsci/docker-plugin#235]
Let's try summarise what is really required to be 1.0:
- [x]  unbundle launchers and add JNLP launcher (allows choosing connection variant with different credentials)  #234 
- [x] connection robustness (reconnections, etc) #150 #230 
- [x] pulling improvements #79 #289 (0.11.0)
- [ ] integrational tests and ath 
- [ ] release JNLP launcher as experimental (should bypass #206 #219)
- [ ] actions for tagging, pushing to registry  https://github.com/jenkinsci/docker-plugin/labels/tag
- [ ] Support for TLS #245 (review as it should work but doesn't?)
- [ ] rework docker builder ( #296 ...)
- [ ] swarm integration ( #299 )
- [x] unbundle docker connection credentials (?)
- [ ] review steps integrations into possible flows (#301)
- [x] load/performance #221 
- [ ] imho migrate to Lists instead arrays and keep data migration (or even wrote new DockerContainerConfiguration or DockerTemplateBase2 class that will have Lists, Describable, migrate to it and simply reuse from other places)
- [ ] share templates configuration between clouds #238
- [x] other refactoring #231
- [ ] Review security
- [ ] check API exposing
- [ ] logging (Docker cloud provisioning is good now, but time measurement logging TODO)
- [ ] ... 
- [ ] functional tests (@lanwen very want to help), after code base will be stable/simplified
- [ ] check/update documentation

I think we can slowly releasing 0.10.0, 0.11.0 and etc with small portions of changes and when everything will work do final 1.0

**Comment by KostyaSha** [comment]
@magnayn @thomassuckow :pager: 
First item was picked suddenly, i found this very interesting and started PoC, then found that UI and Templates part can be simplified.

**Comment by magnayn** [comment]
+1 for doing 0.10.0 etc.

[] It strikes me that the templates should be defined outside of the clouds so they can be reused. (I have a 'build cluster' of 5 or 6 machines, and I end up having to specify the jenkins image for each.

**Comment by KostyaSha** [comment]
@magnayn i think you must use swarm that is compatible by API and can spread containers load.
Btw i will do 0.9.0 today, have good feedback for current master.

**Comment by KostyaSha** [comment]
@magnayn seems i got your idea.

**Comment by KostyaSha** [comment]
If launchers unbundling failure, i will skip it and merge @lanwen commit and continue doing other items.

**Comment by KostyaSha** [comment]
Didn't end small few things, 0.10.1 will be released as soon as i can.

**Comment by KostyaSha** [comment]
Moved integration tests on the first place, i'm slowly designing them, hope other features implementation will be unlocked after it.

**Comment by KostyaSha** [comment]
Shifting 0.16.0 on this weekend as i was very busy :(

**Comment by KostyaSha** [comment]
As soon as @magnayn don't care in cooperation work on this plugin and doing commits into master i don't want maintain/enhance this plugin. Good luck with ASAP commits into master.
